export const APP_DESKTOP_SIDEBAR_LEFT_INSET_PX = 16;
export const APP_DESKTOP_SIDEBAR_WIDTH_PX = 60;
export const APP_DESKTOP_CONTENT_GAP_PX = 16;

export const APP_DESKTOP_CONTENT_OFFSET_PX =
  APP_DESKTOP_SIDEBAR_LEFT_INSET_PX +
  APP_DESKTOP_SIDEBAR_WIDTH_PX +
  APP_DESKTOP_CONTENT_GAP_PX;
